env:
  - DOCKER_COMPOSE_VERSION=1.23.2

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

jobs:
  include:
    - stage: integration tests
      script:
        - docker pull codebattle/js:11.6.0
        - docker pull codebattle/ts:3.5.2
        - docker pull codebattle/golang:1.12.6
        - docker pull codebattle/cpp:17
        - docker pull codebattle/ruby:2.6.0
        - docker pull codebattle/elixir:1.7.3
        - docker pull codebattle/python:3.7.2
        - docker pull codebattle/php:7.3.0
        - docker pull codebattle/clojure:1.10.0
        - docker pull codebattle/haskell:8.4.3
        - docker pull codebattle/perl:5.26.2
        - docker-compose -f services/app/docker-compose.test.yml run sut
    # - stage: build and push docker image
    # if: branch = master
    # script:
    # - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    # - docker build -t codebattle/app --file services/app/Dockerfile.prod services/app/
    # - docker push codebattle/app:latest
