codebattle_port: 4000
codebattle_github_id: "{{ vault_codebattle_github_id }}"
codebattle_github_secret: "{{ vault_codebattle_github_secret }}"
codebattle_discord_id: "{{ vault_codebattle_discord_id }}"
codebattle_discord_secret: "{{ vault_codebattle_discord_secret }}"
codebattle_db_hostname: "{{ vault_codebattle_db_hostname }}"
codebattle_db_username: "{{ vault_codebattle_db_username }}"
codebattle_db_password: "{{ vault_codebattle_db_password }}"
codebattle_db_name: "{{ vault_codebattle_db_name }}"
codebattle_db_port: "{{ vault_codebattle_db_port }}"
codebattle_secret_key_base: "{{ vault_codebattle_secret_key_base }}"
codebattle_live_view_salt: "{{ vault_codebattle_live_view_salt }}"
codebattle_onesignal_app_id: "{{ vault_codebattle_onesignal_app_id }}"
codebattle_onesignal_api_key: "{{ vault_codebattle_onesignal_api_key }}"
codebattle_rollbar_api_key: "9f1dcbb7a9c94769add0a66639cf8bc1"
