codebattle_port: 4000
codebattle_github_id: "22fdd43a4b3766546204"
codebattle_github_secret: "eaac6e0cb603e652a133bde58902507a13cb0901"
codebattle_db_hostname: "db"
codebattle_db_username: "postgres"
codebattle_db_password: ""
codebattle_db_name: "codebattle_dev"
codebattle_db_port: 5432
codebattle_secret_key_base: "asdlskdjalskdjfalksdjfalksjdfalsdjfqwerty"
codebattle_live_view_salt: "asdlskdjalsk"
codebattle_onesignal_app_id: "5857921a-703b-4231-9e0a-bc3e0bb385bb"
codebattle_onesignal_api_key: "NWFkNDczNGUtYTUwZC00ZWI5LWFjNDUtNzlkYzU3YjVlYzA2"
codebattle_rollbar_api_key: "9f1dcbb7a9c94769add0a66639cf8bc1"
