---
- hosts: all
  gather_facts: no

  tasks:
    - name: pull asserts from git
      git:
        repo: https://github.com/hexlet-codebattle/battle_asserts.git
        dest: /home/deploy/battle_asserts
        update: yes
        version: master

    - name: generate issues
      shell:
        cmd: make generate-from-docker
        chdir: /home/deploy/battle_asserts

    - name: mix run upload
      docker_container:
        detach: no
        recreate: yes
        name: codebattle-asserts_uploader
        image: "{{ codebattle_app_image_name }}:latest"
        command: "mix issues.upload /issues_dir"
        state: started
        network_mode: host
        restart_policy: always
        env_file: "{{ codebattle_env_file }}"
        env:
          CODEBATTLE_PORT: "5555"
          MIX_ENV: prod
          NODE_ENV: production
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/var/log/codebattle/:/var/log/codebattle/"
          - "/tmp:/tmp"
          - "/home/deploy/battle_asserts/issues:/issues_dir"
          - "/opt:/opt"
          - "/var/tmp:/var/tmp"
